using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class GenericStringModel
{
    [RealtimeProperty(1, false, true)]
    private string _stringValue;
}
/* ----- Begin Normal Autogenerated Code ----- */
public partial class GenericStringModel : RealtimeModel {
    public string stringValue {
        get {
            return _stringValue;
        }
        set {
            if (_stringValue == value) return;
            _stringValueShouldWrite = true;
            _stringValue = value;
            InvalidateUnreliableLength();
            FireStringValueDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(GenericStringModel model, T value);
    public event PropertyChangedHandler<string> stringValueDidChange;
    
    private bool _stringValueShouldWrite;
    
    public enum PropertyID : uint {
        StringValue = 1,
    }
    
    public GenericStringModel() : this(null) {
    }
    
    public GenericStringModel(RealtimeModel parent) : base(null, parent) {
    }
    
    private void FireStringValueDidChange(string value) {
        try {
            stringValueDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        int length = 0;
        if (context.fullModel) {
            length += WriteStream.WriteStringLength((uint)PropertyID.StringValue, _stringValue);
        } else if (context.unreliableChannel) {
            if (_stringValueShouldWrite) {
                length += WriteStream.WriteStringLength((uint)PropertyID.StringValue, _stringValue);
            }
        }
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var didWriteProperties = false;
        
        if (context.fullModel) {
            stream.WriteString((uint)PropertyID.StringValue, _stringValue);
            _stringValueShouldWrite = false;
        } else if (context.unreliableChannel) {
            if (_stringValueShouldWrite) {
                _stringValueShouldWrite = false;
                stream.WriteString((uint)PropertyID.StringValue, _stringValue);
                didWriteProperties = true;
            }
            
            if (didWriteProperties) InvalidateUnreliableLength();
        }
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            switch (propertyID) {
                case (uint)PropertyID.StringValue: {
                    string previousValue = _stringValue;
                    _stringValue = stream.ReadString();
                    _stringValueShouldWrite = false;
                    if (_stringValue != previousValue) {
                        FireStringValueDidChange(_stringValue);
                    }
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
        }
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
